
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application: 
	name: mircoservercloud-config-ygc-dev

---
spring:
  profiles: test
  application:
	name: mircoservercloud-config-ygc-test
